version: '3.8'
services:

  db:
    image: postgres:16.5-alpine
    environment:
      POSTGRES_DB: rateDB
      POSTGRES_USER: username
      POSTGRES_PASSWORD: superpassword
    ports:
      - "5432:5432"
