"""Initial migrate

Revision ID: fb9a2e7a99ef
Revises: 
Create Date: 2024-11-20 17:20:44.494399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb9a2e7a99ef'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cargo_type', sa.String(), nullable=True),
    sa.Column('rate', sa.Float(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rates_cargo_type'), 'rates', ['cargo_type'], unique=False)
    op.create_index(op.f('ix_rates_effective_date'), 'rates', ['effective_date'], unique=False)
    op.create_index(op.f('ix_rates_id'), 'rates', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rates_id'), table_name='rates')
    op.drop_index(op.f('ix_rates_effective_date'), table_name='rates')
    op.drop_index(op.f('ix_rates_cargo_type'), table_name='rates')
    op.drop_table('rates')
    # ### end Alembic commands ###
